### ISSUE TITLE
SEO Checklist

### ISSUE THREAD

**Issue by bmackley** [lastmjs/javascript-practice#81]
- [ ] URL structure follows /course/topic structure
- [ ] 1-3% of text is a keyword for a page
- [ ] Make sitemap
- [ ] Make sure load times are fast
- [ ] Make sure site is mobile-friendly (https://search.google.com/test/mobile-friendly) 
- [ ] Create a 404 page
- [ ] Use SSL
- [ ] Title tag for every page
- [ ] meta description for every page 
- [ ] Heading for every page
- [ ] Make results easy to share on social media
- [ ] Create a blog
